import type { NiftyStock } from '@/types/stock'

export const NIFTY50_STOCKS: NiftyStock[] = [
  { symbol: 'RELIANCE',   name: 'Reliance Industries',       sector: 'Energy',          keywords: ['reliance', 'ril', 'mukesh ambani', 'jio', 'reliance industries'] },
  { symbol: 'TCS',        name: 'Tata Consultancy Services', sector: 'IT',              keywords: ['tcs', 'tata consultancy', 'tata consulting'] },
  { symbol: 'HDFCBANK',   name: 'HDFC Bank',                 sector: 'Banking',         keywords: ['hdfc bank', 'hdfc', 'hdfcbank'] },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel',             sector: 'Telecom',         keywords: ['airtel', 'bharti airtel', 'bharti'] },
  { symbol: 'ICICIBANK',  name: 'ICICI Bank',                sector: 'Banking',         keywords: ['icici bank', 'icici'] },
  { symbol: 'INFOSYS',    name: 'Infosys',                   sector: 'IT',              keywords: ['infosys', 'infy'] },
  { symbol: 'SBIN',       name: 'State Bank of India',       sector: 'Banking',         keywords: ['sbi', 'state bank', 'state bank of india'] },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever',        sector: 'FMCG',            keywords: ['hindustan unilever', 'hul', 'unilever'] },
  { symbol: 'ITC',        name: 'ITC Limited',               sector: 'FMCG',            keywords: ['itc', 'itc limited'] },
  { symbol: 'LT',         name: 'Larsen & Toubro',           sector: 'Infrastructure',  keywords: ['larsen', 'toubro', 'l&t', 'lt'] },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance',             sector: 'Finance',         keywords: ['bajaj finance', 'bajaj fin'] },
  { symbol: 'HCLTECH',    name: 'HCL Technologies',          sector: 'IT',              keywords: ['hcl', 'hcl tech', 'hcl technologies'] },
  { symbol: 'MARUTI',     name: 'Maruti Suzuki',             sector: 'Auto',            keywords: ['maruti', 'suzuki', 'maruti suzuki'] },
  { symbol: 'SUNPHARMA',  name: 'Sun Pharmaceutical',        sector: 'Pharma',          keywords: ['sun pharma', 'sun pharmaceutical'] },
  { symbol: 'TATAMOTORS', name: 'Tata Motors',               sector: 'Auto',            keywords: ['tata motors', 'tata motor', 'jaguar land rover', 'jlr'] },
  { symbol: 'KOTAKBANK',  name: 'Kotak Mahindra Bank',       sector: 'Banking',         keywords: ['kotak', 'kotak mahindra', 'kotak bank'] },
  { symbol: 'TITAN',      name: 'Titan Company',             sector: 'Consumer',        keywords: ['titan', 'tanishq'] },
  { symbol: 'ONGC',       name: 'Oil & Natural Gas Corp',    sector: 'Energy',          keywords: ['ongc', 'oil and natural gas', 'oil natural gas'] },
  { symbol: 'NTPC',       name: 'NTPC Limited',              sector: 'Power',           keywords: ['ntpc', 'national thermal power'] },
  { symbol: 'POWERGRID',  name: 'Power Grid Corp',           sector: 'Power',           keywords: ['power grid', 'powergrid'] },
  { symbol: 'AXISBANK',   name: 'Axis Bank',                 sector: 'Banking',         keywords: ['axis bank', 'axis'] },
  { symbol: 'WIPRO',      name: 'Wipro',                     sector: 'IT',              keywords: ['wipro'] },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement',          sector: 'Cement',          keywords: ['ultratech', 'ultratech cement'] },
  { symbol: 'NESTLEIND',  name: 'Nestle India',              sector: 'FMCG',            keywords: ['nestle', 'nestle india', 'maggi'] },
  { symbol: 'ASIANPAINT', name: 'Asian Paints',              sector: 'Consumer',        keywords: ['asian paints', 'asian paint'] },
  { symbol: 'TECHM',      name: 'Tech Mahindra',             sector: 'IT',              keywords: ['tech mahindra', 'tech m'] },
  { symbol: 'M&M',        name: 'Mahindra & Mahindra',       sector: 'Auto',            keywords: ['mahindra', 'm&m'] },
  { symbol: 'TATASTEEL',  name: 'Tata Steel',                sector: 'Metals',          keywords: ['tata steel', 'tata steel'] },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv',             sector: 'Finance',         keywords: ['bajaj finserv', 'bajaj financial'] },
  { symbol: 'ADANIENT',   name: 'Adani Enterprises',         sector: 'Conglomerate',    keywords: ['adani enterprises', 'adani group', 'gautam adani'] },
  { symbol: 'ADANIPORTS', name: 'Adani Ports',               sector: 'Infrastructure',  keywords: ['adani ports', 'apsez'] },
  { symbol: 'COALINDIA',  name: 'Coal India',                sector: 'Mining',          keywords: ['coal india', 'coalindia'] },
  { symbol: 'JSWSTEEL',   name: 'JSW Steel',                 sector: 'Metals',          keywords: ['jsw steel', 'jsw'] },
  { symbol: 'GRASIM',     name: 'Grasim Industries',         sector: 'Cement',          keywords: ['grasim', 'grasim industries'] },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank',             sector: 'Banking',         keywords: ['indusind', 'indusind bank'] },
  { symbol: 'DRREDDY',    name: "Dr Reddy's Laboratories",   sector: 'Pharma',          keywords: ["dr reddy", "dr reddy's", 'drreddy'] },
  { symbol: 'CIPLA',      name: 'Cipla',                     sector: 'Pharma',          keywords: ['cipla'] },
  { symbol: 'EICHERMOT',  name: 'Eicher Motors',             sector: 'Auto',            keywords: ['eicher', 'royal enfield', 'eicher motors'] },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp',             sector: 'Auto',            keywords: ['hero motocorp', 'hero moto', 'hero honda'] },
  { symbol: 'BPCL',       name: 'Bharat Petroleum',          sector: 'Energy',          keywords: ['bpcl', 'bharat petroleum'] },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products',    sector: 'FMCG',            keywords: ['tata consumer', 'tata tea', 'tata coffee'] },
  { symbol: 'BRITANNIA',  name: 'Britannia Industries',      sector: 'FMCG',            keywords: ['britannia'] },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals',          sector: 'Healthcare',      keywords: ['apollo hospital', 'apollo hospitals'] },
  { symbol: 'DIVISLAB',   name: "Divi's Laboratories",       sector: 'Pharma',          keywords: ["divi's", 'divis lab', 'divislab'] },
  { symbol: 'HINDALCO',   name: 'Hindalco Industries',       sector: 'Metals',          keywords: ['hindalco', 'hindalco industries'] },
  { symbol: 'SBILIFE',    name: 'SBI Life Insurance',        sector: 'Insurance',       keywords: ['sbi life', 'sbi life insurance'] },
  { symbol: 'HDFCLIFE',   name: 'HDFC Life Insurance',       sector: 'Insurance',       keywords: ['hdfc life', 'hdfc life insurance'] },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto',                sector: 'Auto',            keywords: ['bajaj auto', 'bajaj automobile'] },
  { symbol: 'SHRIRAMFIN', name: 'Shriram Finance',           sector: 'Finance',         keywords: ['shriram finance', 'shriram'] },
  { symbol: 'BEL',        name: 'Bharat Electronics',        sector: 'Defence',         keywords: ['bel', 'bharat electronics'] },
]

export const SECTORS = [...new Set(NIFTY50_STOCKS.map(s => s.sector))]